version: '3.8'

services:
  web:
    build: .
    container_name: checker_domain
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./data/:/usr/src/data/
#    stdin_open: true
#    tty: true
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    volumes:
      - ./postgresql/data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretPASS
      - POSTGRES_DB=user_active
      - DB_PORT=5432
    ports:
      - 5432:5432
