version: '3.8'

services:
  web:
    image: controller
    container_name: checker_domain
    restart: always
    command: runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - migrate

  db:
    image: postgres:14.4-alpine
    volumes:
      - ./postgresql/data/:/var/lib/postgresql/data
    env_file:
      - ./.env.db
    ports:
      - 5432:5432

  migrate:
    image: controller
    restart: on-failure
    command: migrate
    env_file:
      - ./.env.dev
    depends_on:
      - db

  celery:
    image: controller
    entrypoint: ""
    command: celery --app=checkerDomains worker --loglevel=info --logfile=logs/celery.log
    restart: always
    volumes:
      - ./celery/data/:/usr/utils/data/celery
    env_file:
      - ./.env.celery.flower
    depends_on:
      - web
      - redis
      - db

  dashboard:
    image: controller
    entrypoint: ""
    command: celery flower -app=checkerDomains --port=5555 --broker=redis://redis:6379/0
    restart: always
    ports:
      - 5555:5555
    env_file:
      - ./.env.celery.flower
    depends_on:
      - web
      - redis
      - celery
      - db

  redis:
    image: redis:4-alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis/data/:/usr/utils/app
