# Generated by Django 3.2.22 on 2023-11-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDomainsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('created_at', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'user_domains_history',
            },
        ),
        migrations.AddIndex(
            model_name='userdomainshistory',
            index=models.Index(fields=['user_id', 'created_at'], name='user_domain_user_id_8af0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='userdomainshistory',
            index=models.Index(fields=['user_id', 'domain', 'created_at'], name='user_domain_user_id_1a4ca2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdomainshistory',
            unique_together={('user_id', 'domain', 'created_at')},
        ),
    ]
